inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/MutableConstant:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
